"""empty message

Revision ID: 13f487aa64a6
Revises: 494668350270
Create Date: 2014-10-02 15:45:49.727526

"""

# revision identifiers, used by Alembic.
revision = '13f487aa64a6'
down_revision = '494668350270'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
