"""empty message

Revision ID: 14f42ac729c
Revises: a1b4988583d
Create Date: 2014-10-02 14:52:41.709131

"""

# revision identifiers, used by Alembic.
revision = '14f42ac729c'
down_revision = 'a1b4988583d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
