"""empty message

Revision ID: 246d6ff25cae
Revises: 34d2723d48ab
Create Date: 2014-10-01 15:36:55.667223

"""

# revision identifiers, used by Alembic.
revision = '246d6ff25cae'
down_revision = '34d2723d48ab'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
