"""empty message

Revision ID: 31e5a013b72f
Revises: d0389f4b27a
Create Date: 2014-10-01 16:26:20.046857

"""

# revision identifiers, used by Alembic.
revision = '31e5a013b72f'
down_revision = 'd0389f4b27a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
