"""empty message

Revision ID: 34d2723d48ab
Revises: None
Create Date: 2014-09-26 11:36:13.788434

"""

# revision identifiers, used by Alembic.
revision = '34d2723d48ab'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
