"""empty message

Revision ID: 358dd85a5b55
Revises: 3cf120ffa0af
Create Date: 2014-10-03 14:03:42.957482

"""

# revision identifiers, used by Alembic.
revision = '358dd85a5b55'
down_revision = '3cf120ffa0af'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
