"""empty message

Revision ID: 3cf120ffa0af
Revises: 13f487aa64a6
Create Date: 2014-10-02 15:46:39.775933

"""

# revision identifiers, used by Alembic.
revision = '3cf120ffa0af'
down_revision = '13f487aa64a6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
