"""empty message

Revision ID: 3dcbce953c05
Revises: 48e1c287ba95
Create Date: 2014-10-03 15:34:42.734731

"""

# revision identifiers, used by Alembic.
revision = '3dcbce953c05'
down_revision = '48e1c287ba95'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
