"""empty message

Revision ID: 453535c476ab
Revises: 1395b5d5e927
Create Date: 2015-01-17 23:54:48.793088

"""

# revision identifiers, used by Alembic.
revision = '453535c476ab'
down_revision = '1395b5d5e927'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
