"""empty message

Revision ID: 48e1c287ba95
Revises: 358dd85a5b55
Create Date: 2014-10-03 14:23:41.949394

"""

# revision identifiers, used by Alembic.
revision = '48e1c287ba95'
down_revision = '358dd85a5b55'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
