"""empty message

Revision ID: 494668350270
Revises: 4ff42e310db4
Create Date: 2014-10-02 15:43:41.829309

"""

# revision identifiers, used by Alembic.
revision = '494668350270'
down_revision = '4ff42e310db4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
