"""empty message

Revision ID: 4ff42e310db4
Revises: 6af0cadc86c
Create Date: 2014-10-02 15:37:39.019503

"""

# revision identifiers, used by Alembic.
revision = '4ff42e310db4'
down_revision = '6af0cadc86c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
