"""empty message

Revision ID: 56d14932834e
Revises: 14f42ac729c
Create Date: 2014-10-02 14:58:38.702049

"""

# revision identifiers, used by Alembic.
revision = '56d14932834e'
down_revision = '14f42ac729c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
