"""empty message

Revision ID: 6af0cadc86c
Revises: 56d14932834e
Create Date: 2014-10-02 15:29:11.211231

"""

# revision identifiers, used by Alembic.
revision = '6af0cadc86c'
down_revision = '56d14932834e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
