"""empty message

Revision ID: a1b4988583d
Revises: 31e5a013b72f
Create Date: 2014-10-01 16:40:24.070976

"""

# revision identifiers, used by Alembic.
revision = 'a1b4988583d'
down_revision = '31e5a013b72f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
